# Auto-generated by JoseQA — financial analysis function tests
# Uses populated_db fixture (3 months of seeded data)
from __future__ import annotations

import pytest
from datetime import date


# ══════════════════════════════════════════════════════════════════════════════
# get_current_month / get_prev_month (pure, no DB)
# ══════════════════════════════════════════════════════════════════════════════

from tools.analysis.metrics import get_current_month, get_prev_month


class TestGetCurrentMonth:
    def test_returns_yyyy_mm_format(self):
        result = get_current_month()
        assert len(result) == 7
        assert result[4] == "-"

    def test_returns_string(self):
        assert isinstance(get_current_month(), str)

    def test_year_is_reasonable(self):
        year = int(get_current_month()[:4])
        assert 2024 <= year <= 2030

    def test_month_is_valid(self):
        month = int(get_current_month()[5:])
        assert 1 <= month <= 12


class TestGetPrevMonth:
    @pytest.mark.parametrize("month,expected", [
        ("2025-11", "2025-10"),
        ("2025-01", "2024-12"),   # year rollover
        ("2024-12", "2024-11"),
        ("2026-06", "2026-05"),
    ])
    def test_prev_month(self, month, expected):
        assert get_prev_month(month) == expected

    def test_returns_yyyy_mm_format(self):
        result = get_prev_month("2025-10")
        assert len(result) == 7
        assert result[4] == "-"

    def test_no_arg_uses_current_month(self):
        result = get_prev_month()
        assert isinstance(result, str)
        assert len(result) == 7


# ══════════════════════════════════════════════════════════════════════════════
# available_months
# ══════════════════════════════════════════════════════════════════════════════

from tools.analysis.metrics import available_months


class TestAvailableMonths:
    def test_returns_three_months(self, populated_db):
        months = available_months(conn=populated_db)
        assert len(months) == 3

    def test_sorted_descending(self, populated_db):
        months = available_months(conn=populated_db)
        assert months == sorted(months, reverse=True)

    def test_correct_months(self, populated_db):
        months = available_months(conn=populated_db)
        assert "2025-12" in months
        assert "2025-11" in months
        assert "2025-10" in months

    def test_returns_list(self, populated_db):
        assert isinstance(available_months(conn=populated_db), list)

    def test_empty_db_returns_empty(self, db):
        assert available_months(conn=db) == []

    def test_format_is_yyyy_mm(self, populated_db):
        for m in available_months(conn=populated_db):
            assert len(m) == 7
            assert m[4] == "-"


# ══════════════════════════════════════════════════════════════════════════════
# monthly_summary
# ══════════════════════════════════════════════════════════════════════════════

from tools.analysis.metrics import monthly_summary


class TestMonthlySummary:
    def test_returns_dict(self, populated_db):
        result = monthly_summary("2025-10", conn=populated_db)
        assert isinstance(result, dict)

    def test_has_required_keys(self, populated_db):
        result = monthly_summary("2025-10", conn=populated_db)
        keys = set(result.keys())
        assert any(k in keys for k in ("gastos", "total_debits", "spent"))
        assert any(k in keys for k in ("ingresos", "total_credits", "income"))

    def test_gastos_october(self, populated_db):
        # Oct debits: 45000 + 37900 + 15000 + 17900 = 115800
        result = monthly_summary("2025-10", conn=populated_db)
        gastos = result.get("gastos") or result.get("total_debits") or result.get("spent", 0)
        assert gastos == pytest.approx(115_800.0, rel=1e-3)

    def test_ingresos_october(self, populated_db):
        # Oct credit: 5000000 (nómina)
        result = monthly_summary("2025-10", conn=populated_db)
        ingresos = result.get("ingresos") or result.get("total_credits") or result.get("income", 0)
        assert ingresos == pytest.approx(5_000_000.0, rel=1e-3)

    def test_month_field_present(self, populated_db):
        result = monthly_summary("2025-10", conn=populated_db)
        assert "month" in result or "periodo" in result

    def test_empty_month_returns_zeros(self, populated_db):
        result = monthly_summary("2020-01", conn=populated_db)
        gastos = result.get("gastos") or result.get("total_debits") or result.get("spent", 0)
        assert gastos == pytest.approx(0.0)

    def test_no_arg_uses_current_month(self, populated_db):
        result = monthly_summary(conn=populated_db)
        assert isinstance(result, dict)


# ══════════════════════════════════════════════════════════════════════════════
# monthly_trend
# ══════════════════════════════════════════════════════════════════════════════

from tools.analysis.metrics import monthly_trend


class TestMonthlyTrend:
    def test_returns_list(self, populated_db):
        result = monthly_trend(months_back=6, conn=populated_db)
        assert isinstance(result, list)

    def test_returns_three_months(self, populated_db):
        result = monthly_trend(months_back=12, conn=populated_db)
        # We have 3 months of data
        assert len(result) == 3

    def test_each_item_has_month(self, populated_db):
        result = monthly_trend(conn=populated_db)
        for item in result:
            assert "month" in item or any(k for k in item if "month" in k.lower())

    def test_empty_db_returns_empty(self, db):
        result = monthly_trend(conn=db)
        assert result == [] or isinstance(result, list)


# ══════════════════════════════════════════════════════════════════════════════
# category_breakdown_month
# ══════════════════════════════════════════════════════════════════════════════

from tools.analysis.metrics import category_breakdown_month


class TestCategoryBreakdownMonth:
    def test_returns_list(self, populated_db):
        result = category_breakdown_month("2025-10", conn=populated_db)
        assert isinstance(result, list)

    def test_october_has_three_expense_categories(self, populated_db):
        # Oct: Comida (Rappi), Transporte (Uber), Suscripciones (Netflix+Spotify)
        result = category_breakdown_month("2025-10", conn=populated_db)
        # Income category excluded from breakdown
        assert len(result) >= 3

    def test_comida_total_october(self, populated_db):
        result = category_breakdown_month("2025-10", conn=populated_db)
        comida = next(
            (r for r in result if "comida" in str(r.get("name_es", "") or r.get("category", "")).lower()),
            None,
        )
        if comida:
            total = comida.get("total") or comida.get("amount_cop") or comida.get("total_cop", 0)
            assert total == pytest.approx(45_000.0, rel=1e-3)

    def test_no_arg_uses_current(self, populated_db):
        result = category_breakdown_month(conn=populated_db)
        assert isinstance(result, list)

    def test_empty_db_returns_empty(self, db):
        assert category_breakdown_month("2025-10", conn=db) == []


# ══════════════════════════════════════════════════════════════════════════════
# top_merchants
# ══════════════════════════════════════════════════════════════════════════════

from tools.analysis.metrics import top_merchants


class TestTopMerchants:
    def test_returns_list(self, populated_db):
        result = top_merchants(months_back=36, conn=populated_db)
        assert isinstance(result, list)

    def test_excludes_income_transactions(self, populated_db):
        result = top_merchants(months_back=36, conn=populated_db)
        merchants = [r.get("clean_merchant") or r.get("merchant") or "" for r in result]
        # "Nómina" is credit → should not appear in top merchants (debit only)
        assert "Nómina" not in merchants

    def test_rappi_in_top_merchants(self, populated_db):
        result = top_merchants(months_back=36, conn=populated_db)
        all_values = [str(v) for r in result for v in r.values()]
        assert any("Rappi" in v or "RAPPI" in v for v in all_values)

    def test_limit_respected(self, populated_db):
        result = top_merchants(months_back=36, limit=2, conn=populated_db)
        assert len(result) <= 2

    def test_sorted_by_spend_desc(self, populated_db):
        result = top_merchants(months_back=36, conn=populated_db)
        totals = [r.get("total") or r.get("amount_cop") or r.get("total_cop", 0) for r in result]
        assert totals == sorted(totals, reverse=True)


# ══════════════════════════════════════════════════════════════════════════════
# mom_comparison
# ══════════════════════════════════════════════════════════════════════════════

from tools.analysis.metrics import mom_comparison


class TestMomComparison:
    def test_returns_list(self, populated_db):
        result = mom_comparison(months=3, conn=populated_db)
        assert isinstance(result, list)

    def test_has_category_info(self, populated_db):
        result = mom_comparison(months=3, conn=populated_db)
        for item in result:
            assert "category" in item or "name_es" in item or "name" in item

    def test_empty_db_returns_empty_or_list(self, db):
        result = mom_comparison(conn=db)
        assert isinstance(result, list)


# ══════════════════════════════════════════════════════════════════════════════
# Budget functions
# ══════════════════════════════════════════════════════════════════════════════

from tools.analysis.budget import set_budget, get_budget_vs_actual, project_month_end


class TestSetBudget:
    def test_creates_new_budget(self, db):
        db.execute("INSERT INTO categories (id, name, name_es) VALUES (1, 'food', 'Comida')")
        db.commit()
        set_budget(category_id=1, month="2025-10", amount_cop=200_000.0, conn=db)
        row = db.execute("SELECT amount_cop FROM budgets WHERE category_id=1 AND month='2025-10'").fetchone()
        assert row is not None
        assert row[0] == pytest.approx(200_000.0)

    def test_upsert_updates_existing_budget(self, populated_db):
        set_budget(category_id=1, month="2025-10", amount_cop=300_000.0, conn=populated_db)
        row = populated_db.execute(
            "SELECT amount_cop FROM budgets WHERE category_id=1 AND month='2025-10'"
        ).fetchone()
        assert row[0] == pytest.approx(300_000.0)


class TestGetBudgetVsActual:
    def test_returns_list(self, populated_db):
        result = get_budget_vs_actual("2025-10", conn=populated_db)
        assert isinstance(result, list)

    def test_comida_budget_present(self, populated_db):
        result = get_budget_vs_actual("2025-10", conn=populated_db)
        comida = next(
            (r for r in result if "comida" in str(r.get("category") or r.get("name_es") or "").lower()),
            None,
        )
        assert comida is not None

    def test_budget_cop_200000_for_comida(self, populated_db):
        result = get_budget_vs_actual("2025-10", conn=populated_db)
        comida = next(
            (r for r in result if "comida" in str(r.get("category") or r.get("name_es") or "").lower()),
            None,
        )
        if comida:
            budget = comida.get("budget_cop") or comida.get("budget", 0)
            assert budget == pytest.approx(200_000.0, rel=1e-3)

    def test_pct_used_is_float(self, populated_db):
        result = get_budget_vs_actual("2025-10", conn=populated_db)
        for row in result:
            pct = row.get("pct_used") or row.get("pct") or 0
            assert isinstance(pct, (int, float))
            assert 0 <= pct <= 999  # allow over-budget

    def test_spent_cop_matches_transactions(self, populated_db):
        result = get_budget_vs_actual("2025-10", conn=populated_db)
        comida = next(
            (r for r in result if "comida" in str(r.get("category") or r.get("name_es") or "").lower()),
            None,
        )
        if comida:
            spent = comida.get("spent_cop") or comida.get("actual") or comida.get("spent", 0)
            assert spent == pytest.approx(45_000.0, rel=1e-3)

    def test_no_arg_uses_current_month(self, populated_db):
        result = get_budget_vs_actual(conn=populated_db)
        assert isinstance(result, list)


class TestProjectMonthEnd:
    def test_returns_list(self, populated_db):
        result = project_month_end("2025-10", conn=populated_db)
        assert isinstance(result, list)

    def test_has_projected_cop(self, populated_db):
        result = project_month_end("2025-10", conn=populated_db)
        for row in result:
            assert any(k in row for k in ("projected_cop", "projected", "projected_amount"))

    def test_has_days_info(self, populated_db):
        result = project_month_end("2025-10", conn=populated_db)
        for row in result:
            assert any(k in row for k in ("days_elapsed", "days_in_month", "days"))


# ══════════════════════════════════════════════════════════════════════════════
# Subscriptions / recurring detection
# ══════════════════════════════════════════════════════════════════════════════

from tools.analysis.subscriptions import detect_and_mark_recurring, get_recurring_subscriptions


class TestDetectAndMarkRecurring:
    def test_returns_list(self, populated_db):
        result = detect_and_mark_recurring(conn=populated_db)
        assert isinstance(result, list)

    def test_netflix_detected_as_recurring(self, populated_db):
        # Netflix appears in all 3 months with same amount = recurring
        result = detect_and_mark_recurring(conn=populated_db)
        merchants = [str(r.get("merchant") or r.get("clean_merchant") or "") for r in result]
        assert any("Netflix" in m or "NETFLIX" in m for m in merchants)

    def test_spotify_detected_as_recurring(self, populated_db):
        result = detect_and_mark_recurring(conn=populated_db)
        merchants = [str(r.get("merchant") or r.get("clean_merchant") or "") for r in result]
        assert any("Spotify" in m or "SPOTIFY" in m for m in merchants)

    def test_marks_is_recurring_in_db(self, populated_db):
        detect_and_mark_recurring(conn=populated_db)
        rows = populated_db.execute(
            "SELECT COUNT(*) FROM transactions WHERE is_recurring=1"
        ).fetchone()
        assert rows[0] > 0

    def test_empty_db_returns_empty(self, db):
        result = detect_and_mark_recurring(conn=db)
        assert result == [] or isinstance(result, list)


class TestGetRecurringSubscriptions:
    def test_returns_list(self, populated_db):
        detect_and_mark_recurring(conn=populated_db)
        result = get_recurring_subscriptions(conn=populated_db)
        assert isinstance(result, list)

    def test_recurring_merchants_present_after_detection(self, populated_db):
        detect_and_mark_recurring(conn=populated_db)
        result = get_recurring_subscriptions(conn=populated_db)
        merchants = [str(r.get("merchant") or r.get("clean_merchant") or "") for r in result]
        assert any("Netflix" in m or "Spotify" in m for m in merchants)

    def test_empty_before_detection(self, populated_db):
        # Without running detect first, is_recurring=0 for all → empty
        result = get_recurring_subscriptions(conn=populated_db)
        # Depends on whether seed data has is_recurring set
        assert isinstance(result, list)
