# Auto-generated by JoseQA — database query layer tests
# Uses in-memory DB fixture from conftest.py
from __future__ import annotations

import pytest
from datetime import date

from tools.db.queries import (
    upsert_transaction,
    update_transaction_category,
    get_transactions,
    get_categories,
    get_active_rules,
    upsert_rule,
    log_ingest,
    file_already_ingested,
    get_monthly_totals,
    get_category_breakdown,
    get_top_merchants,
)
from tools.ingest.deduplicator import check_duplicates, DedupResult
from tools.ingest.normalizer import Transaction, generate_transaction_id


# ── Test data helpers ─────────────────────────────────────────────────────────

def _tx_dict(**overrides) -> dict:
    base = dict(
        id=generate_transaction_id(date(2025, 10, 5), "RAPPI", 45000.0, "bogota"),
        date=date(2025, 10, 5),
        original_description="RAPPI*DELIVERY",
        clean_merchant="Rappi",
        amount_original=45_000.0,
        currency_original="COP",
        amount_cop=45_000.0,
        fx_rate=1.0,
        transaction_type="debit",
        category_id=None,
        category_source="none",
        source_bank="bogota",
        source_file="test.pdf",
        account_number=None,
        is_recurring=0,
        notes=None,
    )
    base.update(overrides)
    return base


def _seed_category(db, cat_id=1, name="food", name_es="Comida"):
    db.execute(
        "INSERT OR IGNORE INTO categories (id, name, name_es) VALUES (?,?,?)",
        (cat_id, name, name_es),
    )
    db.commit()


# ══════════════════════════════════════════════════════════════════════════════
# upsert_transaction
# ══════════════════════════════════════════════════════════════════════════════

class TestUpsertTransaction:
    def test_inserts_new_transaction(self, db):
        tx = _tx_dict()
        inserted = upsert_transaction(tx, conn=db)
        assert inserted is True

    def test_skips_duplicate_id(self, db):
        tx = _tx_dict()
        upsert_transaction(tx, conn=db)
        inserted_again = upsert_transaction(tx, conn=db)
        assert inserted_again is False

    def test_inserted_row_retrievable(self, db):
        tx = _tx_dict()
        upsert_transaction(tx, conn=db)
        rows = db.execute("SELECT * FROM transactions WHERE id=?", (tx["id"],)).fetchall()
        assert len(rows) == 1

    def test_amount_cop_stored_correctly(self, db):
        tx = _tx_dict(amount_cop=99_999.0)
        upsert_transaction(tx, conn=db)
        row = db.execute("SELECT amount_cop FROM transactions WHERE id=?", (tx["id"],)).fetchone()
        assert row["amount_cop"] == pytest.approx(99_999.0)

    def test_date_stored_as_string_or_date(self, db):
        tx = _tx_dict()
        upsert_transaction(tx, conn=db)
        row = db.execute("SELECT date FROM transactions WHERE id=?", (tx["id"],)).fetchone()
        assert row["date"] is not None

    def test_transaction_type_debit(self, db):
        tx = _tx_dict(transaction_type="debit")
        upsert_transaction(tx, conn=db)
        row = db.execute("SELECT transaction_type FROM transactions WHERE id=?", (tx["id"],)).fetchone()
        assert row["transaction_type"] == "debit"

    def test_transaction_type_credit(self, db):
        tx_id = generate_transaction_id(date(2025, 10, 31), "NOMINA", 5_000_000.0, "bogota")
        tx = _tx_dict(id=tx_id, transaction_type="credit", amount_cop=5_000_000.0)
        upsert_transaction(tx, conn=db)
        row = db.execute("SELECT transaction_type FROM transactions WHERE id=?", (tx["id"],)).fetchone()
        assert row["transaction_type"] == "credit"


# ══════════════════════════════════════════════════════════════════════════════
# update_transaction_category
# ══════════════════════════════════════════════════════════════════════════════

class TestUpdateTransactionCategory:
    def test_updates_category_id(self, db):
        _seed_category(db, cat_id=1)
        tx = _tx_dict(category_id=None)
        upsert_transaction(tx, conn=db)
        update_transaction_category(tx["id"], category_id=1, conn=db)
        row = db.execute("SELECT category_id, category_source FROM transactions WHERE id=?", (tx["id"],)).fetchone()
        assert row["category_id"] == 1

    def test_sets_source_to_manual(self, db):
        _seed_category(db, cat_id=1)
        tx = _tx_dict()
        upsert_transaction(tx, conn=db)
        update_transaction_category(tx["id"], category_id=1, conn=db)
        row = db.execute("SELECT category_source FROM transactions WHERE id=?", (tx["id"],)).fetchone()
        assert row["category_source"] == "manual"


# ══════════════════════════════════════════════════════════════════════════════
# get_transactions — filter combinations
# ══════════════════════════════════════════════════════════════════════════════

class TestGetTransactions:
    def test_returns_all_when_no_filters(self, populated_db):
        rows = get_transactions(conn=populated_db)
        assert len(rows) == 15  # 15 transactions in populated_db

    def test_filter_by_month(self, populated_db):
        rows = get_transactions(filters={"month": "2025-10"}, conn=populated_db)
        assert len(rows) == 5  # 5 transactions in October

    def test_filter_by_transaction_type_debit(self, populated_db):
        rows = get_transactions(filters={"transaction_type": "debit"}, conn=populated_db)
        assert all(r["transaction_type"] == "debit" for r in rows)
        assert len(rows) == 12  # 4 debits × 3 months

    def test_filter_by_transaction_type_credit(self, populated_db):
        rows = get_transactions(filters={"transaction_type": "credit"}, conn=populated_db)
        assert all(r["transaction_type"] == "credit" for r in rows)
        assert len(rows) == 3  # 1 income × 3 months

    def test_filter_by_source_bank(self, populated_db):
        rows = get_transactions(filters={"source_bank": "bogota"}, conn=populated_db)
        assert all(r["source_bank"] == "bogota" for r in rows)
        assert len(rows) > 0

    def test_filter_by_category_id(self, populated_db):
        rows = get_transactions(filters={"category_id": 3}, conn=populated_db)
        assert all(r["category_id"] == 3 for r in rows)
        # Netflix + Spotify = 2 × 3 months = 6
        assert len(rows) == 6

    def test_filter_by_date_range(self, populated_db):
        rows = get_transactions(
            filters={"date_from": "2025-11-01", "date_to": "2025-11-30"},
            conn=populated_db,
        )
        assert len(rows) == 5

    def test_returns_list_of_dicts(self, populated_db):
        rows = get_transactions(conn=populated_db)
        assert isinstance(rows, list)
        assert all(isinstance(r, dict) for r in rows)

    def test_empty_db_returns_empty_list(self, db):
        rows = get_transactions(conn=db)
        assert rows == []


# ══════════════════════════════════════════════════════════════════════════════
# get_categories
# ══════════════════════════════════════════════════════════════════════════════

class TestGetCategories:
    def test_returns_seeded_categories(self, populated_db):
        cats = get_categories(conn=populated_db)
        assert len(cats) == 4  # food, transport, subscriptions, income

    def test_returns_list_of_dicts(self, populated_db):
        cats = get_categories(conn=populated_db)
        assert isinstance(cats, list)
        assert all(isinstance(c, dict) for c in cats)

    def test_empty_db_returns_empty_or_defaults(self, db):
        cats = get_categories(conn=db)
        assert isinstance(cats, list)


# ══════════════════════════════════════════════════════════════════════════════
# get_active_rules
# ══════════════════════════════════════════════════════════════════════════════

class TestGetActiveRules:
    def test_returns_active_rules(self, populated_db):
        rules = get_active_rules(conn=populated_db)
        assert len(rules) == 4  # RAPPI, NETFLIX, UBER, SPOTIFY

    def test_filter_by_bank_scope(self, populated_db):
        rules = get_active_rules(bank="bogota", conn=populated_db)
        # All seeded rules have NULL bank_scope → returned for all banks
        assert isinstance(rules, list)

    def test_returns_list_of_dicts(self, populated_db):
        rules = get_active_rules(conn=populated_db)
        assert all(isinstance(r, dict) for r in rules)

    def test_empty_db_returns_empty(self, db):
        rules = get_active_rules(conn=db)
        assert rules == []


# ══════════════════════════════════════════════════════════════════════════════
# upsert_rule
# ══════════════════════════════════════════════════════════════════════════════

class TestUpsertRule:
    def test_creates_new_rule(self, db):
        _seed_category(db, cat_id=1)
        rule_id = upsert_rule(
            pattern="DIDI",
            match_type="contains",
            category_id=1,
            source="user",
            priority=50,
            bank_scope=None,
            created_from_tx=None,
            conn=db,
        )
        assert isinstance(rule_id, int)
        assert rule_id > 0

    def test_rule_retrievable_after_insert(self, db):
        _seed_category(db, cat_id=1)
        upsert_rule("DIDI", "contains", 1, "user", 50, None, None, conn=db)
        rules = get_active_rules(conn=db)
        patterns = [r["pattern"] for r in rules]
        assert "DIDI" in patterns


# ══════════════════════════════════════════════════════════════════════════════
# file_already_ingested + log_ingest
# ══════════════════════════════════════════════════════════════════════════════

class TestFileAlreadyIngested:
    def test_unknown_hash_returns_false(self, db):
        assert file_already_ingested("nonexistent_hash_xyz", conn=db) is False

    def test_logged_hash_returns_true(self, db):
        entry = dict(
            filename="extracto_oct.pdf",
            file_hash="abc123def456",
            bank="bogota",
            format="pdf",
            rows_extracted=10,
            rows_inserted=10,
            rows_skipped=0,
            status="success",
            error_message=None,
        )
        log_ingest(entry, conn=db)
        assert file_already_ingested("abc123def456", conn=db) is True

    def test_failed_ingest_not_counted_as_ingested(self, db):
        entry = dict(
            filename="broken.pdf",
            file_hash="fail_hash_999",
            bank="bogota",
            format="pdf",
            rows_extracted=0,
            rows_inserted=0,
            rows_skipped=0,
            status="failed",
            error_message="parse error",
        )
        log_ingest(entry, conn=db)
        # Failed ingests: depends on impl — either True (logged) or False (only success counts)
        result = file_already_ingested("fail_hash_999", conn=db)
        assert isinstance(result, bool)


# ══════════════════════════════════════════════════════════════════════════════
# get_monthly_totals / get_category_breakdown / get_top_merchants
# ══════════════════════════════════════════════════════════════════════════════

class TestAggregateQueries:
    def test_get_monthly_totals_returns_list(self, populated_db):
        rows = get_monthly_totals(months_back=12, conn=populated_db)
        assert isinstance(rows, list)
        assert len(rows) == 3  # 3 months of data

    def test_get_monthly_totals_structure(self, populated_db):
        rows = get_monthly_totals(conn=populated_db)
        for row in rows:
            assert "month" in row
            # Amounts should be present
            assert any(k in row for k in ("total_gastos", "gastos", "total_debits", "spent"))

    def test_get_category_breakdown_returns_list(self, populated_db):
        rows = get_category_breakdown("2025-10", conn=populated_db)
        assert isinstance(rows, list)
        assert len(rows) > 0

    def test_get_category_breakdown_october(self, populated_db):
        rows = get_category_breakdown("2025-10", conn=populated_db)
        totals = {r.get("name_es") or r.get("category") or r.get("name"): r for r in rows}
        # Comida: 45000 (Rappi), Suscripciones: 37900+17900=55800, Transporte: 15000
        assert len(rows) >= 3

    def test_get_top_merchants_returns_list(self, populated_db):
        rows = get_top_merchants(months_back=36, limit=10, conn=populated_db)
        assert isinstance(rows, list)
        assert len(rows) > 0

    def test_get_top_merchants_sorted_by_spend(self, populated_db):
        rows = get_top_merchants(months_back=36, limit=10, conn=populated_db)
        totals = [r.get("total_cop") or r.get("total") or r.get("amount_cop") or 0 for r in rows]
        # Should be sorted descending
        assert totals == sorted(totals, reverse=True)


# ══════════════════════════════════════════════════════════════════════════════
# check_duplicates
# ══════════════════════════════════════════════════════════════════════════════

class TestCheckDuplicates:
    def _make_tx(self, tx_id: str, desc: str = "RAPPI") -> Transaction:
        from tools.ingest.normalizer import normalize, _normalize_currency
        from tools.ingest.parsers.base_parser import RawTransaction, BaseParser

        class _P(BaseParser):
            def extract(self, f): return []
            def get_bank_name(self): return "bogota"

        raw = RawTransaction(
            date_raw="2025-10-05",
            description=desc,
            amount_raw="45000",
            currency_raw="COP",
        )
        tx = normalize(raw, bank="bogota", source_file="test.pdf", parser=_P())
        if tx:
            tx.id = tx_id
        return tx

    def test_all_new_when_db_empty(self, db):
        txs = [self._make_tx("id_a", "RAPPI"), self._make_tx("id_b", "NETFLIX")]
        txs = [t for t in txs if t is not None]
        result = check_duplicates(txs, conn=db)
        assert isinstance(result, DedupResult)
        assert len(result.new) == len(txs)
        assert len(result.duplicates) == 0

    def test_existing_id_is_duplicate(self, db):
        # Insert a row directly then check_duplicates detects it
        known_id = "dup_id_known_1"
        upsert_transaction(_tx_dict(id=known_id), conn=db)

        # Build a Transaction object with the same id using _make_tx and override id
        tx = self._make_tx("will_be_overridden")
        if tx is None:
            pytest.skip("normalize returned None")
        tx.id = known_id   # force same ID as what's in DB

        result = check_duplicates([tx], conn=db)
        assert len(result.duplicates) == 1
        assert len(result.new) == 0
