# Auto-generated by JoseQA — merchant cleaning and brand normalization tests
# Pure function tests — no DB, no API
from __future__ import annotations

import pytest

from tools.ingest.merchant_cleaner import clean_merchant
from tools.ingest.brand_normalizer import normalize_brand, build_brand_filter_list


# ══════════════════════════════════════════════════════════════════════════════
# clean_merchant
# ══════════════════════════════════════════════════════════════════════════════

class TestCleanMerchant:

    # ── Payment aggregator prefix stripping ───────────────────────────────────

    @pytest.mark.parametrize("raw,should_not_contain", [
        ("BOLD*RAPPI COLOMBIA",     "BOLD"),
        ("VAULT*NETFLIX",           "VAULT"),
        ("PAYU*SPOTIFY",            "PAYU"),
        ("PYU*AMAZON",              "PYU"),
        ("MERCADO PAGO*DIDI",       "MERCADO PAGO"),
    ])
    def test_strips_aggregator_prefix(self, raw, should_not_contain):
        result = clean_merchant(raw)
        assert should_not_contain.upper() not in result.upper() or result != raw

    # ── Canonical overrides ───────────────────────────────────────────────────

    def test_tienda_d1_canonical(self):
        result = clean_merchant("TIENDA D1 BOGOTA 023")
        assert "D1" in result or "Tiendas D1" in result

    def test_tembici_canonical(self):
        result = clean_merchant("MERCADO PAGO*TEMBICI")
        assert "Tembici" in result or "tembici" in result.lower()

    # ── Length constraint ─────────────────────────────────────────────────────

    def test_max_length_60(self):
        long_desc = "A" * 200 + " BOGOTA TERMINAL 123456 COLOMBIA"
        result = clean_merchant(long_desc)
        assert len(result) <= 60

    # ── Basic normalization ───────────────────────────────────────────────────

    def test_empty_string(self):
        result = clean_merchant("")
        assert isinstance(result, str)

    def test_returns_string(self):
        result = clean_merchant("NETFLIX.COM")
        assert isinstance(result, str)

    def test_result_not_empty_for_valid_input(self):
        result = clean_merchant("RAPPI DELIVERY")
        assert len(result) > 0

    def test_strips_trailing_whitespace(self):
        result = clean_merchant("NETFLIX  ")
        assert result == result.strip()

    # ── City suffix stripping ─────────────────────────────────────────────────

    @pytest.mark.parametrize("raw", [
        "RESTAURANTE EL MAR BOGOTA",
        "SUPERMERCADO JUMBO MEDELLIN",
    ])
    def test_city_suffix_stripped_or_cleaned(self, raw):
        result = clean_merchant(raw)
        # City suffix should either be stripped or result should be shorter
        assert isinstance(result, str)
        assert len(result) <= len(raw)

    # ── Bank-specific cleaning ────────────────────────────────────────────────

    def test_bogota_bank_context(self):
        result = clean_merchant("RAPPI DELIVERY BOGOTA", bank="bogota")
        assert isinstance(result, str)

    def test_itau_bank_context(self):
        result = clean_merchant("NETFLIX COM LATAM", bank="itau")
        assert isinstance(result, str)


# ══════════════════════════════════════════════════════════════════════════════
# normalize_brand
# ══════════════════════════════════════════════════════════════════════════════

class TestNormalizeBrand:

    @pytest.mark.parametrize("raw,expected", [
        # Delivery
        ("Rappi Colombia",       "Rappi"),
        ("RAPPI*DELIVERY",       "Rappi"),
        ("rappi",                "Rappi"),
        # Streaming
        ("NETFLIX.COM",          "Netflix"),
        ("Netflix",              "Netflix"),
        ("SPOTIFY AB",           "Spotify"),
        ("spotify",              "Spotify"),
        ("YOUTUBE PREMIUM",      "YouTube"),
        # Transport
        ("UBER* TRIP",           "Uber"),
        ("uber",                 "Uber"),
        ("DIDI TRANSPORT",       "DiDi"),
        # Food (iFood not in brand map)
        # Retail
        ("AMAZON.COM",           "Amazon"),
        ("MERCADO LIBRE",        "MercadoLibre"),   # no space in canonical
        # Supermarkets
        ("EXITO",                "Éxito"),
        # Tech
        ("APPLE.COM",            "Apple"),
        ("GOOGLE*PLAY",          "Google"),
        # Unknown brand is returned as-is (normalized case)
        ("ZAPATERIA RODRIGUEZ",  "ZAPATERIA RODRIGUEZ"),
    ])
    def test_brand_mapping(self, raw, expected):
        result = normalize_brand(raw)
        assert result == expected

    def test_returns_string(self):
        assert isinstance(normalize_brand("RAPPI"), str)

    def test_empty_string(self):
        result = normalize_brand("")
        assert isinstance(result, str)

    def test_case_insensitive(self):
        assert normalize_brand("netflix") == normalize_brand("NETFLIX")


# ══════════════════════════════════════════════════════════════════════════════
# build_brand_filter_list
# ══════════════════════════════════════════════════════════════════════════════

class TestBuildBrandFilterList:

    def test_deduplicates(self):
        merchants = ["RAPPI", "Rappi", "rappi", "NETFLIX", "Netflix"]
        result = build_brand_filter_list(merchants)
        # Should collapse variations into one canonical brand
        rappi_count = sum(1 for r in result if "rappi" in r.lower())
        assert rappi_count == 1

    def test_returns_list(self):
        result = build_brand_filter_list(["NETFLIX", "SPOTIFY"])
        assert isinstance(result, list)

    def test_empty_input(self):
        result = build_brand_filter_list([])
        assert result == []

    def test_preserves_unknown_brands(self):
        result = build_brand_filter_list(["UNKNOWN_SHOP_XYZ"])
        assert len(result) >= 1

    def test_sorted_or_consistent_order(self):
        merchants = ["SPOTIFY", "NETFLIX", "RAPPI"]
        result = build_brand_filter_list(merchants)
        assert len(result) > 0  # ordering may vary by impl

    def test_all_items_are_strings(self):
        result = build_brand_filter_list(["RAPPI", "NETFLIX", "UBER"])
        assert all(isinstance(r, str) for r in result)
