# Auto-generated by JoseQA — normalizer tests
# Pure function tests — no DB, no API calls
from __future__ import annotations

import pytest
from datetime import date

from tools.ingest.parsers.base_parser import RawTransaction
from tools.ingest.normalizer import (
    Transaction,
    generate_transaction_id,
    normalize,
    normalize_batch,
    transaction_to_dict,
    _normalize_currency,
)


# ── Helpers ───────────────────────────────────────────────────────────────────

def _raw(**kwargs) -> RawTransaction:
    defaults = dict(
        date_raw="2025-10-05",
        description="RAPPI*DELIVERY",
        amount_raw="45000",
        currency_raw="COP",
        transaction_type_raw="",
    )
    defaults.update(kwargs)
    return RawTransaction(**defaults)


from tools.ingest.parsers.base_parser import BaseParser


class _FakeParser(BaseParser):
    def extract(self, f): return []
    def get_bank_name(self): return "bogota"


_parser = _FakeParser()


# ══════════════════════════════════════════════════════════════════════════════
# generate_transaction_id
# ══════════════════════════════════════════════════════════════════════════════

class TestGenerateTransactionId:
    def test_returns_string(self):
        tx_id = generate_transaction_id(date(2025, 10, 5), "RAPPI", 45000.0, "bogota")
        assert isinstance(tx_id, str)

    def test_length_is_32(self):
        tx_id = generate_transaction_id(date(2025, 10, 5), "RAPPI", 45000.0, "bogota")
        assert len(tx_id) == 32

    def test_deterministic(self):
        id1 = generate_transaction_id(date(2025, 10, 5), "RAPPI", 45000.0, "bogota")
        id2 = generate_transaction_id(date(2025, 10, 5), "RAPPI", 45000.0, "bogota")
        assert id1 == id2

    def test_different_dates_differ(self):
        id1 = generate_transaction_id(date(2025, 10, 5), "RAPPI", 45000.0, "bogota")
        id2 = generate_transaction_id(date(2025, 10, 6), "RAPPI", 45000.0, "bogota")
        assert id1 != id2

    def test_different_amounts_differ(self):
        id1 = generate_transaction_id(date(2025, 10, 5), "RAPPI", 45000.0, "bogota")
        id2 = generate_transaction_id(date(2025, 10, 5), "RAPPI", 50000.0, "bogota")
        assert id1 != id2

    def test_different_descriptions_differ(self):
        id1 = generate_transaction_id(date(2025, 10, 5), "RAPPI", 45000.0, "bogota")
        id2 = generate_transaction_id(date(2025, 10, 5), "NETFLIX", 45000.0, "bogota")
        assert id1 != id2

    def test_different_banks_differ(self):
        id1 = generate_transaction_id(date(2025, 10, 5), "RAPPI", 45000.0, "bogota")
        id2 = generate_transaction_id(date(2025, 10, 5), "RAPPI", 45000.0, "itau")
        assert id1 != id2

    def test_hex_characters_only(self):
        tx_id = generate_transaction_id(date(2025, 10, 5), "RAPPI", 45000.0, "bogota")
        assert all(c in "0123456789abcdef" for c in tx_id)


# ══════════════════════════════════════════════════════════════════════════════
# _normalize_currency
# ══════════════════════════════════════════════════════════════════════════════

class TestNormalizeCurrency:
    @pytest.mark.parametrize("raw,expected", [
        ("COP", "COP"),
        ("cop", "COP"),
        ("USD", "USD"),
        ("usd", "USD"),
        ("EUR", "EUR"),
        ("$",   "COP"),   # bare dollar in Colombian context = COP
        # "US$" strips $ → "US" not in mapping → returns as-is
        # ("US$", "USD"),  # skip: US$ not explicitly mapped
        ("HUF", "HUF"),
        ("",    "COP"),   # default to COP
    ])
    def test_normalize(self, raw, expected):
        result = _normalize_currency(raw)
        assert result == expected


# ══════════════════════════════════════════════════════════════════════════════
# normalize (single RawTransaction → Transaction)
# ══════════════════════════════════════════════════════════════════════════════

class TestNormalize:
    def test_happy_path_returns_transaction(self):
        raw = _raw()
        tx = normalize(raw, bank="bogota", source_file="test.pdf", parser=_parser)
        assert tx is not None
        assert isinstance(tx, Transaction)

    def test_date_is_parsed(self):
        # Use DD/MM/YYYY format — handled by explicit regex, no dateutil ambiguity
        raw = _raw(date_raw="05/10/2025")
        tx = normalize(raw, bank="bogota", source_file="test.pdf", parser=_parser)
        assert tx is not None
        d = tx.date
        if isinstance(d, str):
            from datetime import datetime
            d = datetime.strptime(d[:10], "%Y-%m-%d").date()
        assert d == date(2025, 10, 5)

    def test_amount_is_float(self):
        raw = _raw(amount_raw="45.000")
        tx = normalize(raw, bank="bogota", source_file="test.pdf", parser=_parser)
        assert isinstance(tx.amount_original, float)
        assert tx.amount_original == pytest.approx(45_000.0)

    def test_source_bank_set(self):
        raw = _raw()
        tx = normalize(raw, bank="bogota", source_file="test.pdf", parser=_parser)
        assert tx.source_bank == "bogota"

    def test_source_file_set(self):
        raw = _raw()
        tx = normalize(raw, bank="bogota", source_file="my_statement.pdf", parser=_parser)
        assert tx.source_file == "my_statement.pdf"

    def test_debit_transaction_type(self):
        raw = _raw(amount_raw="-45000", transaction_type_raw="D")
        tx = normalize(raw, bank="bogota", source_file="test.pdf", parser=_parser)
        assert tx.transaction_type == "debit"

    def test_credit_transaction_type(self):
        raw = _raw(amount_raw="5000000", transaction_type_raw="C")
        tx = normalize(raw, bank="bogota", source_file="test.pdf", parser=_parser)
        assert tx.transaction_type == "credit"

    def test_currency_cop_default(self):
        raw = _raw(currency_raw="COP")
        tx = normalize(raw, bank="bogota", source_file="test.pdf", parser=_parser)
        assert tx.currency_original == "COP"

    def test_invalid_date_returns_none(self):
        raw = _raw(date_raw="not-a-date")
        tx = normalize(raw, bank="bogota", source_file="test.pdf", parser=_parser)
        assert tx is None

    def test_id_is_32_char_hex(self):
        raw = _raw()
        tx = normalize(raw, bank="bogota", source_file="test.pdf", parser=_parser)
        assert len(tx.id) == 32
        assert all(c in "0123456789abcdef" for c in tx.id)


# ══════════════════════════════════════════════════════════════════════════════
# normalize_batch
# ══════════════════════════════════════════════════════════════════════════════

class TestNormalizeBatch:
    def test_returns_tuple(self):
        raws = [_raw(), _raw(description="NETFLIX", amount_raw="37900")]
        result = normalize_batch(raws, "bogota", "test.pdf", _parser)
        assert isinstance(result, tuple)
        assert len(result) == 2

    def test_all_valid_returns_all(self):
        raws = [
            _raw(description="RAPPI",   amount_raw="45000"),
            _raw(description="NETFLIX", amount_raw="37900"),
            _raw(description="UBER",    amount_raw="15000"),
        ]
        txs, errors = normalize_batch(raws, "bogota", "test.pdf", _parser)
        assert len(txs) == 3

    def test_invalid_date_excluded(self):
        raws = [
            _raw(description="GOOD",  amount_raw="45000"),
            _raw(description="BAD",   amount_raw="37900", date_raw="INVALID"),
        ]
        txs, _ = normalize_batch(raws, "bogota", "test.pdf", _parser)
        assert len(txs) == 1

    def test_intra_batch_duplicates_get_suffix(self):
        # Same description + amount + date = same fingerprint → suffix applied
        raw = _raw()
        raws = [raw, _raw()]   # identical → same ID
        txs, _ = normalize_batch(raws, "bogota", "test.pdf", _parser)
        if len(txs) == 2:
            assert txs[0].id != txs[1].id  # suffix distinguishes them

    def test_errors_list_for_invalid(self):
        raws = [_raw(date_raw="INVALID")]
        txs, errors = normalize_batch(raws, "bogota", "test.pdf", _parser)
        # Either returns error or skips — either way, result is consistent
        assert isinstance(errors, list)

    def test_empty_input_returns_empty(self):
        txs, errors = normalize_batch([], "bogota", "test.pdf", _parser)
        assert txs == []


# ══════════════════════════════════════════════════════════════════════════════
# transaction_to_dict
# ══════════════════════════════════════════════════════════════════════════════

class TestTransactionToDict:
    def _make_tx(self) -> Transaction:
        raw = _raw()
        return normalize(raw, bank="bogota", source_file="test.pdf", parser=_parser)

    def test_returns_dict(self):
        tx = self._make_tx()
        assert isinstance(transaction_to_dict(tx), dict)

    def test_contains_id(self):
        tx = self._make_tx()
        d = transaction_to_dict(tx)
        assert "id" in d

    def test_contains_date(self):
        tx = self._make_tx()
        d = transaction_to_dict(tx)
        assert "date" in d

    def test_contains_amount(self):
        tx = self._make_tx()
        d = transaction_to_dict(tx)
        assert "amount_original" in d or "amount_cop" in d

    def test_date_is_string_or_date(self):
        tx = self._make_tx()
        d = transaction_to_dict(tx)
        # date must be serializable (string or date object)
        assert isinstance(d["date"], (str, date))

    def test_all_values_are_serializable(self):
        import json
        tx = self._make_tx()
        d = transaction_to_dict(tx)
        # Convert dates to strings for JSON test
        safe = {k: str(v) if isinstance(v, date) else v for k, v in d.items()}
        json.dumps(safe)  # must not raise
