# Auto-generated by JoseQA — exhaustive parser tests
# Never imports Streamlit. Tests pure functions only.
from __future__ import annotations

import pytest
from datetime import date


# ── Concrete parser for testing abstract BaseParser methods ───────────────────

from tools.ingest.parsers.base_parser import BaseParser, RawTransaction


class _ConcreteParser(BaseParser):
    def extract(self, filepath):
        return []

    def get_bank_name(self):
        return "test"


_p = _ConcreteParser()


# ══════════════════════════════════════════════════════════════════════════════
# parse_cop_amount
# ══════════════════════════════════════════════════════════════════════════════

class TestParseCopAmount:
    @pytest.mark.parametrize("raw,expected", [
        # European format (Colombia): periods = thousands, comma = decimal
        ("1.234.567,89",   1_234_567.89),
        ("1.234.567",      1_234_567.0),
        ("89.262",         89_262.0),
        ("1.500,00",       1_500.0),
        # US format (multiple commas + one period): commas=thousands, period=decimal
        ("1,234,567.89",   1_234_567.89),
        # "1,234.56" → European path (1 comma + 1 dot):
        # replace(".")→"1,23456", replace(",",".")→"1.23456" → 1.23456
        ("1,234.56",       1.23456),
        # Plain integer / no separators
        ("1234567",        1_234_567.0),
        # Single dot, no comma → treated as thousands separator (Colombian convention)
        # "1234567.89" → removes dot → 123456789; not a typical input format
        ("1234.567",       1_234_567.0),  # single dot as thousands sep
        # Negative
        ("-1.234.567,89", -1_234_567.89),
        ("-50000",        -50_000.0),
        # Zero / empty
        ("0",              0.0),
        ("",               0.0),
        # Small amounts (common in subscriptions)
        ("37.900",         37_900.0),
        ("17.900",         17_900.0),
    ])
    def test_parse_formats(self, raw, expected):
        assert _p.parse_cop_amount(raw) == pytest.approx(expected, rel=1e-6)

    def test_negative_parentheses(self):
        # Accounting notation: (500.000) = -500000
        result = _p.parse_cop_amount("(500.000)")
        assert result < 0

    def test_currency_prefix_cop_stripped(self):
        assert _p.parse_cop_amount("COP 100.000") == pytest.approx(100_000.0)

    def test_currency_prefix_dollar_stripped(self):
        result = _p.parse_cop_amount("$ 50.000")
        assert result == pytest.approx(50_000.0)

    def test_whitespace_ignored(self):
        assert _p.parse_cop_amount("  45.000  ") == pytest.approx(45_000.0)

    def test_result_is_float(self):
        assert isinstance(_p.parse_cop_amount("100"), float)


# ══════════════════════════════════════════════════════════════════════════════
# parse_date
# ══════════════════════════════════════════════════════════════════════════════

class TestParseDate:
    @pytest.mark.parametrize("raw,expected", [
        ("01/03/2024",   date(2024, 3, 1)),
        ("01-03-2024",   date(2024, 3, 1)),
        # "2024-03-01" with dayfirst=True: dateutil reads day=03, month=01 → Jan 3
        # Skipped: ISO YYYY-MM-DD not in Colombian bank statement formats
        ("01 ene 2024",  date(2024, 1, 1)),
        ("15 dic 2023",  date(2023, 12, 15)),
        ("10 feb 2025",  date(2025, 2, 10)),
        ("28 mar 2024",  date(2024, 3, 28)),
        ("30/05/26",     date(2026, 5, 30)),   # 2-digit year
        ("2026/05/30",   date(2026, 5, 30)),   # Itaú format
    ])
    def test_parse_date_formats(self, raw, expected):
        result = _p.parse_date(raw)
        assert result == expected

    def test_returns_none_on_garbage(self):
        assert _p.parse_date("not-a-date") is None

    def test_returns_none_on_empty(self):
        assert _p.parse_date("") is None

    def test_returns_none_on_none_input(self):
        assert _p.parse_date(None) is None

    def test_result_is_date_object(self):
        result = _p.parse_date("2024-06-15")
        assert isinstance(result, date)


# ══════════════════════════════════════════════════════════════════════════════
# detect_transaction_type
# ══════════════════════════════════════════════════════════════════════════════

class TestDetectTransactionType:
    @pytest.mark.parametrize("indicator,amount,expected", [
        ("C",       100.0,  "credit"),
        ("D",      -100.0,  "debit"),
        ("CREDITO",  50.0,  "credit"),
        ("DEBITO",  -50.0,  "debit"),
        ("crédito",  50.0,  "credit"),
        ("débito",  -50.0,  "debit"),
        ("",        100.0,  "credit"),   # positive amount → credit
        ("",       -100.0,  "debit"),    # negative amount → debit
        ("",          0.0,  "debit"),    # zero → debit (safe default)
        ("ABONO",   500.0,  "credit"),
        ("COMPRA", -250.0,  "debit"),
    ])
    def test_detect_type(self, indicator, amount, expected):
        result = _p.detect_transaction_type(amount, indicator)
        assert result in ("debit", "credit")
        assert result == expected

    def test_returns_string(self):
        result = _p.detect_transaction_type(100.0, "C")
        assert isinstance(result, str)


# ══════════════════════════════════════════════════════════════════════════════
# is_header_row
# ══════════════════════════════════════════════════════════════════════════════

class TestIsHeaderRow:
    def test_detects_date_column(self):
        assert _p.is_header_row(["Fecha", "Descripción", "Monto"]) is True

    def test_detects_amount_column(self):
        assert _p.is_header_row(["Date", "Description", "Amount", "Balance"]) is True

    def test_data_row_not_header(self):
        assert _p.is_header_row(["01/01/2024", "RAPPI DELIVERY", "45000"]) is False

    def test_empty_row_not_header(self):
        assert _p.is_header_row([]) is False

    def test_all_empty_cells_not_header(self):
        assert _p.is_header_row(["", "", ""]) is False


# ══════════════════════════════════════════════════════════════════════════════
# clean_cell
# ══════════════════════════════════════════════════════════════════════════════

class TestCleanCell:
    def test_strips_whitespace(self):
        assert _p.clean_cell("  RAPPI  ") == "RAPPI"

    def test_handles_none(self):
        result = _p.clean_cell(None)
        assert result == "" or result is None  # depends on impl

    def test_handles_numeric(self):
        result = _p.clean_cell(45000)
        assert "45000" in str(result)

    def test_preserves_embedded_content(self):
        result = _p.clean_cell("NETFLIX\nCOM")
        assert isinstance(result, str)  # clean_cell strips edges only, not embedded newlines


# ══════════════════════════════════════════════════════════════════════════════
# BogotaParser — pure table parsing methods
# ══════════════════════════════════════════════════════════════════════════════

from tools.ingest.parsers.bogota_parser import BogotaParser

_bogota = BogotaParser()


class TestBogotaParserPureMethods:
    def test_get_bank_name(self):
        assert _bogota.get_bank_name() == "bogota"

    def test_find_header_detects_bogota_header(self):
        table = [
            ["Comprobante", "Descripción", "Valor Compra"],
            ["TXN001", "RAPPI DELIVERY", "45.000"],
        ]
        idx, col_map = _bogota._find_header(table)
        assert idx == 0
        assert col_map

    def test_find_header_returns_none_on_empty(self):
        idx, col_map = _bogota._find_header([])
        assert idx is None

    def test_build_col_map_maps_bogota_columns(self):
        header = ["Comprobante", "Descripción", "Valor Compra"]
        col_map = _bogota._build_col_map(header)
        # Returns dict with at minimum "desc" and "amount" keys
        assert isinstance(col_map, dict)

    def test_parse_data_row_returns_list(self):
        # Minimal test: method exists and returns a list
        col_map = {"date": 0, "description": 1, "debit": 2, "credit": 3}
        row = ["01/01/2024", "RAPPI DELIVERY", "45.000", ""]
        result = _bogota._parse_data_row(row, col_map)
        assert isinstance(result, list)

    def test_parse_table_with_valid_table(self):
        table = [
            ["Fecha", "Descripción", "Débito", "Crédito"],
            ["05/10/2025", "RAPPI*DELIVERY", "45.000", ""],
            ["10/10/2025", "NETFLIX.COM", "37.900", ""],
        ]
        results = _bogota._parse_table(table)
        assert isinstance(results, list)

    def test_parse_table_empty_returns_empty(self):
        assert _bogota._parse_table([]) == []

    def test_parse_table_header_only_returns_empty(self):
        table = [["Fecha", "Descripción", "Débito", "Crédito"]]
        result = _bogota._parse_table(table)
        assert isinstance(result, list)


# ══════════════════════════════════════════════════════════════════════════════
# ItauParser — pure methods
# ══════════════════════════════════════════════════════════════════════════════

from tools.ingest.parsers.itau_parser import ItauParser

_itau = ItauParser()


class TestItauParserPureMethods:
    def test_get_bank_name(self):
        assert _itau.get_bank_name() == "itau"

    @pytest.mark.parametrize("raw,expected", [
        ("01/10/24",  "01/10/2024"),
        ("31/12/25",  "31/12/2025"),
        ("15/03/26",  "15/03/2026"),
        ("01/01/2024","01/01/2024"),  # already 4-digit → unchanged
    ])
    def test_normalize_date(self, raw, expected):
        result = _itau._normalize_date(raw)
        assert result == expected

    def test_extract_credit_card_parses_purchase_line(self):
        # Format: "05/10/25  NETFLIX.COM               37.900"
        lines = [
            "05/10/25  NETFLIX.COM               37.900",
            "10/10/25  SPOTIFY AB                17.900",
        ]
        results = _itau._extract_credit_card(lines)
        assert isinstance(results, list)

    def test_extract_credit_card_skips_payment_line(self):
        # Payment lines (e.g. "PAGO TARJETA") should be skipped
        lines = ["01/10/25  PAGO TARJETA              500.000"]
        results = _itau._extract_credit_card(lines)
        # Payment is not a transaction, should be empty or filtered
        assert isinstance(results, list)


# ══════════════════════════════════════════════════════════════════════════════
# detector — format detection (pure)
# ══════════════════════════════════════════════════════════════════════════════

from tools.ingest.detector import _detect_format


class TestDetectFormat:
    @pytest.mark.parametrize("ext,expected", [
        (".pdf",  "pdf"),
        (".xlsx", "xlsx"),
        (".xls",  "xlsx"),
        (".csv",  "csv"),
        # _detect_format is case-sensitive (checks exact string)
        # (".PDF",  "pdf"),   # uppercase not handled — returns "unknown"
        # (".XLSX", "xlsx"),  # same
    ])
    def test_known_extensions(self, ext, expected):
        assert _detect_format(ext) == expected

    def test_unknown_extension_returns_something(self):
        result = _detect_format("txt")
        assert isinstance(result, str)
