# Auto-generated by JoseQA — review before applying
# Project: Personal finance Manager
# Tests pure functions directly — never imports Streamlit
from __future__ import annotations

import sqlite3
import pytest
from unittest.mock import MagicMock, patch


# ── Schema DDL ────────────────────────────────────────────────────────────────

_SCHEMA = """
CREATE TABLE IF NOT EXISTS categories (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    name        TEXT UNIQUE NOT NULL,
    name_es     TEXT NOT NULL,
    icon        TEXT DEFAULT '💳',
    color       TEXT DEFAULT '#808080',
    is_income   INTEGER DEFAULT 0,
    created_at  DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
    id                  TEXT PRIMARY KEY,
    date                DATE NOT NULL,
    original_description TEXT NOT NULL,
    clean_merchant      TEXT,
    amount_original     REAL NOT NULL,
    currency_original   TEXT NOT NULL DEFAULT 'COP',
    amount_cop          REAL,
    fx_rate             REAL DEFAULT 1.0,
    transaction_type    TEXT CHECK(transaction_type IN ('debit','credit')) DEFAULT 'debit',
    category_id         INTEGER REFERENCES categories(id),
    category_source     TEXT CHECK(category_source IN ('rule','claude','manual','none')) DEFAULT 'none',
    source_bank         TEXT NOT NULL,
    source_file         TEXT,
    account_number      TEXT,
    is_recurring        INTEGER DEFAULT 0,
    notes               TEXT,
    created_at          DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at          DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_transactions_date     ON transactions(date);
CREATE INDEX IF NOT EXISTS idx_transactions_category ON transactions(category_id);
CREATE INDEX IF NOT EXISTS idx_transactions_bank     ON transactions(source_bank);
CREATE INDEX IF NOT EXISTS idx_transactions_merchant ON transactions(clean_merchant);

CREATE TABLE IF NOT EXISTS categorization_rules (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    pattern         TEXT NOT NULL,
    match_type      TEXT CHECK(match_type IN ('exact','contains','regex')) DEFAULT 'contains',
    category_id     INTEGER NOT NULL REFERENCES categories(id),
    bank_scope      TEXT,
    priority        INTEGER DEFAULT 100,
    is_active       INTEGER DEFAULT 1,
    source          TEXT CHECK(source IN ('system','user','claude')) DEFAULT 'system',
    created_from_tx TEXT REFERENCES transactions(id),
    created_at      DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_rules_priority ON categorization_rules(priority, is_active);

CREATE TABLE IF NOT EXISTS fx_rates (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    date            DATE NOT NULL,
    from_currency   TEXT NOT NULL,
    to_currency     TEXT NOT NULL DEFAULT 'COP',
    rate            REAL NOT NULL,
    source          TEXT DEFAULT 'api',
    fetched_at      DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(date, from_currency, to_currency)
);

CREATE TABLE IF NOT EXISTS budgets (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    category_id INTEGER NOT NULL REFERENCES categories(id),
    month       TEXT NOT NULL,
    amount_cop  REAL NOT NULL,
    created_at  DATETIME DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(category_id, month)
);

CREATE TABLE IF NOT EXISTS alerts (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    alert_type      TEXT NOT NULL,
    category_id     INTEGER REFERENCES categories(id),
    month           TEXT,
    message         TEXT NOT NULL,
    threshold       REAL,
    actual_value    REAL,
    is_dismissed    INTEGER DEFAULT 0,
    created_at      DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS chat_messages (
    id          INTEGER PRIMARY KEY AUTOINCREMENT,
    role        TEXT CHECK(role IN ('user','assistant')) NOT NULL,
    content     TEXT NOT NULL,
    sql_query   TEXT,
    created_at  DATETIME DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS ingest_log (
    id              INTEGER PRIMARY KEY AUTOINCREMENT,
    filename        TEXT NOT NULL,
    file_hash       TEXT NOT NULL UNIQUE,
    bank            TEXT,
    format          TEXT,
    rows_extracted  INTEGER DEFAULT 0,
    rows_inserted   INTEGER DEFAULT 0,
    rows_skipped    INTEGER DEFAULT 0,
    status          TEXT CHECK(status IN ('success','partial','failed')),
    error_message   TEXT,
    ingested_at     DATETIME DEFAULT CURRENT_TIMESTAMP
);
"""

# ── Base DB fixture ───────────────────────────────────────────────────────────


@pytest.fixture
def db():
    """Empty in-memory SQLite with full schema — never touches finance.db."""
    conn = sqlite3.connect(":memory:")
    conn.row_factory = sqlite3.Row
    conn.execute("PRAGMA journal_mode=WAL")
    conn.execute("PRAGMA foreign_keys=ON")
    conn.executescript(_SCHEMA)
    conn.commit()
    yield conn
    conn.close()


# ── Populated DB fixture ──────────────────────────────────────────────────────

_SEED_CATEGORIES = [
    (1, "food",          "Comida",       "🍽️", "#f59e0b", 0),
    (2, "transport",     "Transporte",   "🚗", "#06b6d4", 0),
    (3, "subscriptions", "Suscripciones","📱", "#8b5cf6", 0),
    (4, "income",        "Ingresos",     "💰", "#22c55e", 1),
]

# 5 transactions per month × 3 months = 15 debit + 3 credit = 18 rows
_SEED_TRANSACTIONS = [
    # October 2025
    ("oct_1", "2025-10-05", "RAPPI*DELIVERY",  "Rappi",   45_000, "COP",  45_000, 1.0, "debit",  1, "rule", "bogota"),
    ("oct_2", "2025-10-10", "NETFLIX.COM",     "Netflix", 37_900, "COP",  37_900, 1.0, "debit",  3, "rule", "itau"),
    ("oct_3", "2025-10-15", "UBER TRIP",       "Uber",    15_000, "COP",  15_000, 1.0, "debit",  2, "rule", "bogota"),
    ("oct_4", "2025-10-20", "SPOTIFY AB",      "Spotify", 17_900, "COP",  17_900, 1.0, "debit",  3, "rule", "itau"),
    ("oct_i", "2025-10-31", "NOMINA OCTUBRE",  "Nómina",5_000_000,"COP",5_000_000,1.0,"credit",  4, "rule", "bogota"),
    # November 2025
    ("nov_1", "2025-11-05", "RAPPI*DELIVERY",  "Rappi",   52_000, "COP",  52_000, 1.0, "debit",  1, "rule", "bogota"),
    ("nov_2", "2025-11-10", "NETFLIX.COM",     "Netflix", 37_900, "COP",  37_900, 1.0, "debit",  3, "rule", "itau"),
    ("nov_3", "2025-11-15", "UBER TRIP",       "Uber",    18_000, "COP",  18_000, 1.0, "debit",  2, "rule", "bogota"),
    ("nov_4", "2025-11-20", "SPOTIFY AB",      "Spotify", 17_900, "COP",  17_900, 1.0, "debit",  3, "rule", "itau"),
    ("nov_i", "2025-11-30", "NOMINA NOVIEMBRE","Nómina",5_000_000,"COP",5_000_000,1.0,"credit",  4, "rule", "bogota"),
    # December 2025
    ("dec_1", "2025-12-05", "RAPPI*DELIVERY",  "Rappi",   61_000, "COP",  61_000, 1.0, "debit",  1, "rule", "bogota"),
    ("dec_2", "2025-12-10", "NETFLIX.COM",     "Netflix", 37_900, "COP",  37_900, 1.0, "debit",  3, "rule", "itau"),
    ("dec_3", "2025-12-15", "UBER TRIP",       "Uber",    12_000, "COP",  12_000, 1.0, "debit",  2, "rule", "bogota"),
    ("dec_4", "2025-12-20", "SPOTIFY AB",      "Spotify", 17_900, "COP",  17_900, 1.0, "debit",  3, "rule", "itau"),
    ("dec_i", "2025-12-31", "NOMINA DICIEMBRE","Nómina",5_000_000,"COP",5_000_000,1.0,"credit",  4, "rule", "bogota"),
]

_SEED_BUDGETS = [
    (1, "2025-10", 200_000),
    (1, "2025-11", 200_000),
    (1, "2025-12", 200_000),
    (2, "2025-10", 100_000),
]

_SEED_RULES = [
    ("RAPPI",   "contains", 1, None, 10, 1, "system"),
    ("NETFLIX", "contains", 3, None, 20, 1, "system"),
    ("UBER",    "contains", 2, None, 30, 1, "system"),
    ("SPOTIFY", "contains", 3, None, 40, 1, "system"),
]


@pytest.fixture
def populated_db(db):
    """In-memory DB pre-loaded with 3 months of test data, budgets, and rules."""
    db.executemany(
        "INSERT INTO categories (id, name, name_es, icon, color, is_income) VALUES (?,?,?,?,?,?)",
        _SEED_CATEGORIES,
    )
    db.executemany(
        """INSERT INTO transactions
           (id, date, original_description, clean_merchant, amount_original,
            currency_original, amount_cop, fx_rate, transaction_type,
            category_id, category_source, source_bank)
           VALUES (?,?,?,?,?,?,?,?,?,?,?,?)""",
        _SEED_TRANSACTIONS,
    )
    db.executemany(
        "INSERT INTO budgets (category_id, month, amount_cop) VALUES (?,?,?)",
        _SEED_BUDGETS,
    )
    db.executemany(
        """INSERT INTO categorization_rules
           (pattern, match_type, category_id, bank_scope, priority, is_active, source)
           VALUES (?,?,?,?,?,?,?)""",
        _SEED_RULES,
    )
    db.commit()
    yield db


# ── Redirect get_connection() to in-memory fixture ───────────────────────────


@pytest.fixture(autouse=True)
def patch_db_connection(db, monkeypatch):
    """Redirect get_connection() and close_connection() to the in-memory fixture DB."""
    monkeypatch.setattr("tools.db.connection.get_connection", lambda: db)
    monkeypatch.setattr("tools.db.connection.close_connection", lambda: None)


# ── Claude API mock ───────────────────────────────────────────────────────────


@pytest.fixture
def mock_claude():
    """Mock AsyncAnthropic AND synchronous Anthropic — prevents real API calls."""
    fake_resp = MagicMock()
    fake_resp.content = [MagicMock(text='["otros"]', type="text")]
    fake_resp.stop_reason = "end_turn"

    with patch("anthropic.Anthropic") as MockSync, \
         patch("anthropic.AsyncAnthropic") as MockAsync:
        sync_client = MagicMock()
        sync_client.messages.create.return_value = fake_resp
        MockSync.return_value = sync_client

        from unittest.mock import AsyncMock
        async_client = AsyncMock()
        async_client.messages.create = AsyncMock(return_value=fake_resp)
        MockAsync.return_value = async_client

        yield sync_client, async_client
