# Auto-generated by JoseQA — chat assistant and NL→SQL tests
# Claude API always mocked — no real API calls
from __future__ import annotations

import json
import pytest
from unittest.mock import MagicMock, patch

from tools.chat.query_builder import nl_to_sql, validate_sql, SQLQueryResult
from tools.chat.context_builder import build_context_snapshot, execute_safe_query


# ══════════════════════════════════════════════════════════════════════════════
# nl_to_sql — validate_sql is the security gate (pure); nl_to_sql calls Claude
# ══════════════════════════════════════════════════════════════════════════════

class TestNlToSqlMocked:
    """nl_to_sql calls Anthropic → mock it in every test."""

    def _mock_claude(self, sql_text: str, explanation: str = "test"):
        fake = MagicMock()
        fake.content = [MagicMock(
            text=json.dumps({"sql": sql_text, "explanation": explanation}),
            type="text",
        )]
        return fake

    def test_returns_sqlqueryresult(self):
        with patch("tools.chat.query_builder.anthropic.Anthropic") as MockClient:
            client = MagicMock()
            client.messages.create.return_value = self._mock_claude(
                "SELECT * FROM transactions LIMIT 10"
            )
            MockClient.return_value = client
            result = nl_to_sql("¿Cuánto gasté este mes?")
        assert isinstance(result, SQLQueryResult)

    def test_valid_sql_is_safe(self):
        with patch("tools.chat.query_builder.anthropic.Anthropic") as MockClient:
            client = MagicMock()
            client.messages.create.return_value = self._mock_claude(
                "SELECT SUM(amount_cop) FROM transactions WHERE transaction_type='debit'"
            )
            MockClient.return_value = client
            result = nl_to_sql("¿Cuánto gasté?")
        assert result.is_safe is True
        assert result.sql != ""

    def test_unsafe_sql_from_claude_blocked(self):
        with patch("tools.chat.query_builder.anthropic.Anthropic") as MockClient:
            client = MagicMock()
            client.messages.create.return_value = self._mock_claude(
                "DROP TABLE transactions"
            )
            MockClient.return_value = client
            result = nl_to_sql("Borra todo")
        assert result.is_safe is False

    def test_non_whitelisted_table_blocked(self):
        with patch("tools.chat.query_builder.anthropic.Anthropic") as MockClient:
            client = MagicMock()
            client.messages.create.return_value = self._mock_claude(
                "SELECT * FROM ingest_log"
            )
            MockClient.return_value = client
            result = nl_to_sql("Muestra los logs")
        assert result.is_safe is False

    def test_error_when_no_api_key(self, monkeypatch):
        monkeypatch.delenv("ANTHROPIC_API_KEY", raising=False)
        result = nl_to_sql("¿Qué gasté?")
        assert result.is_safe is False
        assert result.error != ""

    def test_explanation_returned(self):
        with patch("tools.chat.query_builder.anthropic.Anthropic") as MockClient:
            client = MagicMock()
            client.messages.create.return_value = self._mock_claude(
                "SELECT * FROM transactions LIMIT 5",
                explanation="Muestra las últimas 5 transacciones",
            )
            MockClient.return_value = client
            result = nl_to_sql("Muéstrame transacciones")
        assert isinstance(result.explanation, str)

    def test_malformed_json_from_claude_handled(self):
        fake = MagicMock()
        fake.content = [MagicMock(text="not json at all", type="text")]
        with patch("tools.chat.query_builder.anthropic.Anthropic") as MockClient:
            client = MagicMock()
            client.messages.create.return_value = fake
            MockClient.return_value = client
            result = nl_to_sql("¿Gastos?")
        assert result.is_safe is False
        assert result.error != ""

    def test_empty_sql_from_claude_blocked(self):
        with patch("tools.chat.query_builder.anthropic.Anthropic") as MockClient:
            client = MagicMock()
            client.messages.create.return_value = self._mock_claude("")
            MockClient.return_value = client
            result = nl_to_sql("¿Gastos?")
        assert result.is_safe is False

    @pytest.mark.parametrize("question", [
        "¿Cuánto gasté en Rappi este mes?",
        "¿Cuál fue mi gasto total en octubre?",
        "Muéstrame las suscripciones del último mes",
        "¿Cuánto gasté en transporte?",
        "¿Cuál es mi balance del mes?",
    ])
    def test_typical_questions_dont_crash(self, question):
        with patch("tools.chat.query_builder.anthropic.Anthropic") as MockClient:
            client = MagicMock()
            client.messages.create.return_value = MagicMock(
                content=[MagicMock(
                    text='{"sql": "SELECT * FROM transactions LIMIT 5", "explanation": "test"}',
                    type="text",
                )]
            )
            MockClient.return_value = client
            result = nl_to_sql(question)
        assert isinstance(result, SQLQueryResult)


# ══════════════════════════════════════════════════════════════════════════════
# build_context_snapshot — rich text snapshot from DB
# ══════════════════════════════════════════════════════════════════════════════

class TestBuildContextSnapshot:
    def test_returns_string(self, populated_db):
        result = build_context_snapshot(conn=populated_db)
        assert isinstance(result, str)

    def test_not_empty_with_data(self, populated_db):
        result = build_context_snapshot(conn=populated_db)
        assert len(result) > 100

    def test_empty_db_returns_no_data_message(self, db):
        result = build_context_snapshot(conn=db)
        assert isinstance(result, str)
        assert "no hay" in result.lower() or len(result) < 200

    def test_contains_month_info(self, populated_db):
        result = build_context_snapshot(conn=populated_db)
        assert "2025" in result

    def test_contains_merchant_data(self, populated_db):
        result = build_context_snapshot(conn=populated_db)
        # At least one of the seeded merchants should appear
        assert any(m in result for m in ("Rappi", "Netflix", "RAPPI", "NETFLIX", "Spotify"))

    def test_contains_financial_amounts(self, populated_db):
        result = build_context_snapshot(conn=populated_db)
        # COP amounts should be visible (formatted numbers)
        assert "COP" in result or "cop" in result.lower() or "$" in result or "000" in result

    def test_contains_category_breakdown(self, populated_db):
        result = build_context_snapshot(conn=populated_db)
        # Category section should be present
        assert "Comida" in result or "categor" in result.lower()

    def test_contains_subscription_section(self, populated_db):
        result = build_context_snapshot(conn=populated_db)
        # Subscriptions section — Netflix/Spotify appear in 3 months
        assert "Netflix" in result or "Spotify" in result or "suscripc" in result.lower()

    def test_result_is_markdown(self, populated_db):
        result = build_context_snapshot(conn=populated_db)
        # Should contain markdown table or headers
        assert "#" in result or "|" in result


# ══════════════════════════════════════════════════════════════════════════════
# ChatAssistant.chat — full conversation flow, Claude mocked
# ══════════════════════════════════════════════════════════════════════════════

from tools.chat.assistant import ChatAssistant


class TestChatAssistant:
    def _make_assistant(self, db):
        return ChatAssistant(conn=db)

    def test_instantiates(self, populated_db):
        assistant = self._make_assistant(populated_db)
        assert assistant is not None

    def test_chat_returns_dict(self, populated_db):
        fake_resp = MagicMock()
        fake_resp.content = [MagicMock(text="Tu gasto fue $115,800 COP en octubre.", type="text")]
        fake_resp.stop_reason = "end_turn"

        with patch("anthropic.Anthropic") as MockSync, \
             patch("anthropic.AsyncAnthropic") as MockAsync:
            sync_client = MagicMock()
            sync_client.messages.create.return_value = fake_resp
            MockSync.return_value = sync_client
            MockAsync.return_value = MagicMock()

            assistant = self._make_assistant(populated_db)
            result = assistant.chat("¿Cuánto gasté en octubre?")

        assert isinstance(result, dict)

    def test_chat_has_answer_key(self, populated_db):
        fake_resp = MagicMock()
        fake_resp.content = [MagicMock(text="Respuesta de prueba.", type="text")]
        fake_resp.stop_reason = "end_turn"

        with patch("anthropic.Anthropic") as MockClient:
            client = MagicMock()
            client.messages.create.return_value = fake_resp
            MockClient.return_value = client

            assistant = self._make_assistant(populated_db)
            result = assistant.chat("¿Qué gasté?")

        assert "answer" in result or "respuesta" in result or isinstance(result.get("answer"), str)

    def test_chat_stores_message_in_db(self, populated_db):
        fake_resp = MagicMock()
        fake_resp.content = [MagicMock(text="Respuesta.", type="text")]
        fake_resp.stop_reason = "end_turn"

        with patch("anthropic.Anthropic") as MockClient:
            client = MagicMock()
            client.messages.create.return_value = fake_resp
            MockClient.return_value = client

            assistant = self._make_assistant(populated_db)
            assistant.chat("¿Qué gasté?")

        count = populated_db.execute("SELECT COUNT(*) FROM chat_messages").fetchone()[0]
        assert count >= 1

    def test_chat_with_empty_db_does_not_crash(self, db):
        fake_resp = MagicMock()
        fake_resp.content = [MagicMock(text="No hay datos todavía.", type="text")]
        fake_resp.stop_reason = "end_turn"

        with patch("anthropic.Anthropic") as MockClient:
            client = MagicMock()
            client.messages.create.return_value = fake_resp
            MockClient.return_value = client

            assistant = self._make_assistant(db)
            result = assistant.chat("¿Cuánto gasté?")

        assert isinstance(result, dict)

    def test_multiple_turns_dont_crash(self, populated_db):
        fake_resp = MagicMock()
        fake_resp.content = [MagicMock(text="Ok.", type="text")]
        fake_resp.stop_reason = "end_turn"

        with patch("anthropic.Anthropic") as MockClient:
            client = MagicMock()
            client.messages.create.return_value = fake_resp
            MockClient.return_value = client

            assistant = self._make_assistant(populated_db)
            for q in ["¿Cuánto gasté?", "¿En qué categoría?", "¿Y el mes pasado?"]:
                result = assistant.chat(q)
                assert isinstance(result, dict)
